In [13]:
# =========================
# Address cleaning & standardization
# =========================
import re

_ABBR_MAP = [
   (r"\bbrgy\b", "barangay"),
   (r"\bbrg[y.]?\b", "barangay"),
   (r"\bst\b", "street"),
   (r"\brd\b", "road"),
   (r"\bave\b", "avenue"),
   (r"\bav\b", "avenue"),
   (r"\bblvd\b", "boulevard"),
   (r"\bflr\b", "floor"),
   (r"\bph\b", "penthouse"),
]

# High-signal Manila terms
_SYNONYM_MAP = [
   (r"\bbgc\b", "bonifacio global city"),
   (r"\bfort\b", "fort bonifacio"),
   (r"\bmakati\s*cbd\b", "makati central business district"),
   (r"\bqc\b", "quezon city"),
]

# Words that rarely help geocoders and often add noise; remove as standalone tokens
_NOISE_TOKENS = [
   "condominium", "condominiums", "residences", "residence", "tower", "towers",
   "phase", "blk", "block", "lot", "unit", "bldg", "building", "subdivision",
   "village"  # keep if it's the only locator; we handle cautiously below
]
def _normalize_space(s: str) -> str:
   s = re.sub(r"[,\|;/\\]+", " ", s)      # unify separators to space
   s = re.sub(r"\s+", " ", s).strip()
   return s

def _strip_diacritics_basic(s: str) -> str:
   return (s.replace("ñ", "n")
            .replace("á","a").replace("à","a").replace("â","a")
            .replace("é","e").replace("è","e").replace("ê","e")
            .replace("í","i").replace("ì","i").replace("î","i")
            .replace("ó","o").replace("ò","o").replace("ô","o")
            .replace("ú","u").replace("ù","u").replace("û","u"))

def _apply_map_pairs(s: str, pairs) -> str:
   for pat, repl in pairs:
       s = re.sub(pat, repl, s)
   return s

def clean_address_freeform(addr: str) -> str:
   """
   Conservative cleaner for a single-string address.
   Keeps districts/landmarks like 'Ayala Triangle' or 'Greenbelt' if no street exists.
   """
   if not addr:
       return ""
   x = _normalize_space(_strip_diacritics_basic(addr.lower()))
   # Expand abbreviations and synonyms
   x = _apply_map_pairs(x, _ABBR_MAP)
   x = _apply_map_pairs(x, _SYNONYM_MAP)
   tokens = x.split(" ")
   # If we have a street number / street keyword, we can safely drop noise tokens
   has_street_signal = any(t.isdigit() for t in tokens) or any(
       kw in x for kw in ["street", "road", "avenue", "drive", "highway", "hwy", "lane"]
   )
   if has_street_signal:
       tokens = [t for t in tokens if t not in _NOISE_TOKENS]
   x = " ".join(tokens)
   x = _normalize_space(x)
   return x

def compose_query(address: str,
                 city: str = "",
                 barangay: str = "",
                 force_metro_manila_tail: bool = True) -> str:
   """
   Build a geocode query with optional admin tail.
   If city/barangay are present, append them; otherwise pass address as-is.
   """
   parts = []
   addr_clean = clean_address_freeform(address)
   if addr_clean:
       parts.append(addr_clean)
   brgy_clean = clean_address_freeform(barangay) if barangay else ""
   city_clean = clean_address_freeform(city) if city else ""
   # Avoid duplicating if already included
   if brgy_clean and brgy_clean not in addr_clean:
       parts.append(brgy_clean)
   if city_clean and city_clean not in addr_clean:
       parts.append(city_clean)
   if force_metro_manila_tail:
       tail = "metro manila philippines"
       if tail not in addr_clean:
           parts.append(tail)
   q = _normalize_space(" ".join(parts))
   return q

In [14]:
import pandas as pd

# read csv file 'data-properties-with-corrections' and save to dataframe df
df = pd.read_csv('data_properties/data-properties-with-corrections.csv')

# Add full_address column
df['full_address'] = df['project_name'] + ", " + df['location'] + ", Philippines"

df.head()

,project_name,location,full_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,..."
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ..."
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man..."
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp..."
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ..."

In [15]:
# add a new column 'cleaned_address' to df by applying the function 'compose_query' to the column 'full_address'
df['cleaned_address'] = df['full_address'].apply(compose_query)
df.head()

,project_name,location,full_address,cleaned_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...

In [16]:
df

,project_name,location,full_address,cleaned_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...
...,...,...,...,...
1011,dakotaresidences,"Tugatog, Malabon, Metro Manila","dakotaresidences, Tugatog, Malabon, Metro Mani...",dakotaresidences tugatog malabon metro manila ...
1012,mckinley hill garden villas,"Bagong Tanyag, Taguig, Metro Manila","mckinley hill garden villas, Bagong Tanyag, Ta...",mckinley hill garden villas bagong tanyag tagu...
1013,oriental gardens makati,"Bangkal, Makati, Metro Manila","oriental gardens makati, Bangkal, Makati, Metr...",oriental gardens makati bangkal makati metro m...
1014,symfoni kamias,"Ramon Magsaysay, Quezon City, Metro Manila","symfoni kamias, Ramon Magsaysay, Quezon City, ...",symfoni kamias ramon magsaysay quezon city met...
1015,trump tower,"Makati, Metro Manila","trump tower, Makati, Metro Manila, Philippines",trump tower makati metro manila philippines

In [17]:
import requests, typing as T

# =========================
# Config
# =========================

# Metro Manila bounding box (lon_min, lat_min, lon_max, lat_max)
MM_BBOX = (120.85, 14.00, 121.20, 14.90)

GOOGLE_KEY = "AIzaSyATTWZx0JUPqeaHjm718D0SZsrA5T16kOI"
COUNTRY_2 = "PH"  # Philippines

# =========================
# Helpers
# =========================

def in_bbox(lon: float, lat: float, bbox=MM_BBOX) -> bool:
   x0, y0, x1, y1 = bbox
   return (x0 <= lon <= x1) and (y0 <= lat <= y1)

# =========================
# Google Geocoding (quality-filtered)
# =========================
def geocode_google(address: str, country_2: str = COUNTRY_2) -> T.Optional[dict]:
   if not GOOGLE_KEY:
       return None  # silently skip if no key
   url = "https://maps.googleapis.com/maps/api/geocode/json"
   params = {
       "address": address,
       "components": f"country:{country_2}",
       "key": GOOGLE_KEY,
   }
   r = requests.get(url, params=params, timeout=30)
   r.raise_for_status()
   data = r.json()
   if data.get("status") != "OK":
       return None
   # Keep only ROOFTOP or GEOMETRIC_CENTER
   for res in data.get("results", []):
       loc = res.get("geometry", {}).get("location", {})
       lt = res.get("geometry", {}).get("location_type", "")
       if lt not in {"ROOFTOP", "GEOMETRIC_CENTER"}:
           continue
       lat = float(loc.get("lat"))
       lon = float(loc.get("lng"))
       if not in_bbox(lon, lat):
           continue
       return {
           "provider": "google",
           "formatted_address": res.get("formatted_address", ""),
           "lat": lat,
           "lon": lon,
           "location_type": lt,
           "place_id": res.get("place_id"),
           "types": ",".join(res.get("types", []))
       }
   return None

In [ ]:
# Add a new column 'geocode_clean' to df by applying the function 'geocode_google' to the column 'cleaned_address'
# Add a new column 'geocode_full' to df by applying the function 'geocode_google' to the column 'full_address'
df['geocode_clean'] = df['cleaned_address'].apply(geocode_google)
df['geocode_full'] = df['full_address'].apply(geocode_google)
df.head()

,project_name,location,full_address,cleaned_address,geocode_google
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...,"{'provider': 'google', 'formatted_address': '1..."
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...,"{'provider': 'google', 'formatted_address': '1..."
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines,"{'provider': 'google', 'formatted_address': 'C..."
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...,"{'provider': 'google', 'formatted_address': '1..."
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...,"{'provider': 'google', 'formatted_address': '1..."

In [12]:
df

,project_name,location,full_address,cleaned_address,geocode_google
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...,"{'provider': 'google', 'formatted_address': '1..."
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...,"{'provider': 'google', 'formatted_address': '1..."
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines,"{'provider': 'google', 'formatted_address': 'C..."
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...,"{'provider': 'google', 'formatted_address': '1..."
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...,"{'provider': 'google', 'formatted_address': '1..."
...,...,...,...,...,...
1011,dakotaresidences,"Tugatog, Malabon, Metro Manila","dakotaresidences, Tugatog, Malabon, Metro Mani...",dakotaresidences tugatog malabon metro manila ...,"{'provider': 'google', 'formatted_address': '6..."
1012,mckinley hill garden villas,"Bagong Tanyag, Taguig, Metro Manila","mckinley hill garden villas, Bagong Tanyag, Ta...",mckinley hill garden villas bagong tanyag tagu...,"{'provider': 'google', 'formatted_address': 'V..."
1013,oriental gardens makati,"Bangkal, Makati, Metro Manila","oriental gardens makati, Bangkal, Makati, Metr...",oriental gardens makati bangkal makati metro m...,"{'provider': 'google', 'formatted_address': 'L..."
1014,symfoni kamias,"Ramon Magsaysay, Quezon City, Metro Manila","symfoni kamias, Ramon Magsaysay, Quezon City, ...",symfoni kamias ramon magsaysay quezon city met...,"{'provider': 'google', 'formatted_address': 'K..."
1015,trump tower,"Makati, Metro Manila","trump tower, Makati, Metro Manila, Philippines",trump tower makati metro manila philippines,"{'provider': 'google', 'formatted_address': 'M..."