In [47]:
# =========================
# Address cleaning & standardization
# =========================
import re

_ABBR_MAP = [
   (r"\bbrgy\b", "barangay"),
   (r"\bbrg[y.]?\b", "barangay"),
   (r"\bst\b", "street"),
   (r"\brd\b", "road"),
   (r"\bave\b", "avenue"),
   (r"\bav\b", "avenue"),
   (r"\bblvd\b", "boulevard"),
   (r"\bflr\b", "floor"),
   (r"\bph\b", "penthouse"),
]

# High-signal Manila terms
_SYNONYM_MAP = [
   (r"\bbgc\b", "bonifacio global city"),
   (r"\bfort\b", "fort bonifacio"),
   (r"\bmakati\s*cbd\b", "makati central business district"),
   (r"\bqc\b", "quezon city"),
]

# Words that rarely help geocoders and often add noise; remove as standalone tokens
_NOISE_TOKENS = [
   "condominium", "condominiums", "residences", "residence", "tower", "towers",
   "phase", "blk", "block", "lot", "unit", "bldg", "building", "subdivision",
   "village"  # keep if it's the only locator; we handle cautiously below
]
def _normalize_space(s: str) -> str:
   s = re.sub(r"[,\|;/\\]+", " ", s)      # unify separators to space
   s = re.sub(r"\s+", " ", s).strip()
   return s

def _strip_diacritics_basic(s: str) -> str:
   return (s.replace("ñ", "n")
            .replace("á","a").replace("à","a").replace("â","a")
            .replace("é","e").replace("è","e").replace("ê","e")
            .replace("í","i").replace("ì","i").replace("î","i")
            .replace("ó","o").replace("ò","o").replace("ô","o")
            .replace("ú","u").replace("ù","u").replace("û","u"))

def _apply_map_pairs(s: str, pairs) -> str:
   for pat, repl in pairs:
       s = re.sub(pat, repl, s)
   return s

def clean_address_freeform(addr: str) -> str:
   """
   Conservative cleaner for a single-string address.
   Keeps districts/landmarks like 'Ayala Triangle' or 'Greenbelt' if no street exists.
   """
   if not addr:
       return ""
   x = _normalize_space(_strip_diacritics_basic(addr.lower()))
   # Expand abbreviations and synonyms
   x = _apply_map_pairs(x, _ABBR_MAP)
   x = _apply_map_pairs(x, _SYNONYM_MAP)
   tokens = x.split(" ")
   # If we have a street number / street keyword, we can safely drop noise tokens
   has_street_signal = any(t.isdigit() for t in tokens) or any(
       kw in x for kw in ["street", "road", "avenue", "drive", "highway", "hwy", "lane"]
   )
   if has_street_signal:
       tokens = [t for t in tokens if t not in _NOISE_TOKENS]
   x = " ".join(tokens)
   x = _normalize_space(x)
   return x

def compose_query(address: str,
                 city: str = "",
                 barangay: str = "",
                 force_mm_tail: bool = True) -> str:
   """
   Build a geocode query with optional admin tail.
   If city/barangay are present, append them; otherwise pass address as-is.
   """
   parts = []
   addr_clean = clean_address_freeform(address)
   if addr_clean:
       parts.append(addr_clean)
   brgy_clean = clean_address_freeform(barangay) if barangay else ""
   city_clean = clean_address_freeform(city) if city else ""
   # Avoid duplicating if already included
   if brgy_clean and brgy_clean not in addr_clean:
       parts.append(brgy_clean)
   if city_clean and city_clean not in addr_clean:
       parts.append(city_clean)
   if force_mm_tail:
       tail = "metro manila philippines"
       if tail not in addr_clean:
           parts.append(tail)
   q = _normalize_space(" ".join(parts))
   return q

In [48]:
import pandas as pd

# read csv file 'data-properties-with-corrections' and save to dataframe df
df = pd.read_csv('data_properties/data-properties-with-corrections.csv')

# Add full_address column
df['full_address'] = df['project_name'] + ", " + df['location'] + ", Philippines"

df.head()

,project_name,location,full_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,..."
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ..."
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man..."
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp..."
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ..."

In [49]:
# add a new column 'cleaned_address' to df by applying the function 'compose_query' to the column 'full_address'
df['cleaned_address'] = df['full_address'].apply(compose_query)
df.head()

,project_name,location,full_address,cleaned_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...

In [50]:
df

,project_name,location,full_address,cleaned_address
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...
...,...,...,...,...
1011,dakotaresidences,"Tugatog, Malabon, Metro Manila","dakotaresidences, Tugatog, Malabon, Metro Mani...",dakotaresidences tugatog malabon metro manila ...
1012,mckinley hill garden villas,"Bagong Tanyag, Taguig, Metro Manila","mckinley hill garden villas, Bagong Tanyag, Ta...",mckinley hill garden villas bagong tanyag tagu...
1013,oriental gardens makati,"Bangkal, Makati, Metro Manila","oriental gardens makati, Bangkal, Makati, Metr...",oriental gardens makati bangkal makati metro m...
1014,symfoni kamias,"Ramon Magsaysay, Quezon City, Metro Manila","symfoni kamias, Ramon Magsaysay, Quezon City, ...",symfoni kamias ramon magsaysay quezon city met...
1015,trump tower,"Makati, Metro Manila","trump tower, Makati, Metro Manila, Philippines",trump tower makati metro manila philippines

In [51]:
import time, requests, typing as T, geopandas as gpd
from shapely.geometry import Point

# =========================
# Config
# =========================

GOOGLE_KEY = "AIzaSyATTWZx0JUPqeaHjm718D0SZsrA5T16kOI"
COUNTRY_2 = "PH"
USER_AGENT = "PH-Geocoder/1.0 (contact: dvpagcaliwagan@up.edu.ph)"

# Metro Manila bounding box (lon_min, lat_min, lon_max, lat_max)
MM_BBOX = (120.85, 14.00, 121.20, 14.90)

SOURCE_CRS = "EPSG:4326"   # WGS84
ANALYSIS_CRS = "EPSG:32651"  # UTM Zone 51N
MAX_RETRIES = 4
BACKOFF_BASE_SEC = 1.5

# =========================
# Utility functions
# =========================

def in_bbox(lon: float, lat: float, bbox=MM_BBOX) -> bool:
   x0, y0, x1, y1 = bbox
   return (x0 <= lon <= x1) and (y0 <= lat <= y1)

def backoff_sleep(try_idx: int):
   delay = BACKOFF_BASE_SEC * (2 ** try_idx)
   time.sleep(delay + 0.25 * (try_idx + 1))

In [52]:
# =========================
# Google Geocoding API
# =========================

def google_geocode_request(query: str, country_2: str = COUNTRY_2) -> dict:
   if not GOOGLE_KEY:
       raise RuntimeError("GOOGLE_MAPS_API_KEY not set.")
   url = "https://maps.googleapis.com/maps/api/geocode/json"
   params = {
       "address": query,
       "components": f"country:{country_2}",
       "key": GOOGLE_KEY,
   }
   headers = {"User-Agent": USER_AGENT}
   last_err = None
   for t in range(MAX_RETRIES):
       try:
           r = requests.get(url, params=params, headers=headers, timeout=30)
           r.raise_for_status()
           data = r.json()
           status = data.get("status", "")
           if status == "OK":
               return data
           elif status in {"OVER_DAILY_LIMIT", "OVER_QUERY_LIMIT", "UNKNOWN_ERROR"}:
               backoff_sleep(t)
               last_err = RuntimeError(f"Google status: {status}")
               continue
           elif status == "ZERO_RESULTS":
               return data
           else:
               raise RuntimeError(f"Google status: {status}, error: {data.get('error_message')}")
       except requests.RequestException as e:
           last_err = e
           backoff_sleep(t)
   if last_err:
       raise last_err
   return {"status": "ZERO_RESULTS", "results": []}

def pick_google_candidate(results: list) -> T.Optional[dict]:
   for r in results:
       if r.get("partial_match", False):
           continue
       geom = r.get("geometry", {})
       lt = geom.get("location_type", "")
       if lt not in {"ROOFTOP", "GEOMETRIC_CENTER"}:
           continue
       loc = geom.get("location", {})
       lat = float(loc.get("lat"))
       lon = float(loc.get("lng"))
       if not in_bbox(lon, lat):
           continue
       return {
           "provider": "google",
           "formatted_address": r.get("formatted_address", ""),
           "lat": lat,
           "lon": lon,
           "location_type": lt,
           "place_id": r.get("place_id"),
           "types": ",".join(r.get("types", []))
       }
   return None

def geocode_google_quality(query: str) -> T.Optional[dict]:
   data = google_geocode_request(query)
   if data.get("status") != "OK":
       return None
   return pick_google_candidate(data.get("results", []))

In [53]:
# =========================
# Batch pipeline (Google only + fallback)
# =========================

def geocode_google_batch(
   df: pd.DataFrame,
   full_address_col: str,
   city_col: T.Optional[str] = None,
   barangay_col: T.Optional[str] = None,
   force_mm_tail: bool = True
) -> pd.DataFrame:
   out = df.copy()
   for c in ["cleaned_query", "fallback_query", "lat", "lon", "geocode_provider", "formatted_address", "quality_note"]:
       if c not in out.columns:
           out[c] = pd.NA
   for i, row in out.iterrows():
       full_address = str(row[full_address_col]) if pd.notna(row[full_address_col]) else ""
       raw_city = str(row[city_col]) if city_col and pd.notna(row[city_col]) else ""
       raw_brgy = str(row[barangay_col]) if barangay_col and pd.notna(row[barangay_col]) else ""
       
       # Primary query: cleaned address
       cleaned_query = compose_query(full_address, city=raw_city, barangay=raw_brgy, force_mm_tail=force_mm_tail)
       out.at[i, "cleaned_query"] = cleaned_query
       if not cleaned_query:
           continue
       try:
           res = geocode_google_quality(cleaned_query)
       except Exception as e:
           print(f"[WARN] Google error row {i} cleaned: {e}")
           res = None
       # Fallback: use full raw address if cleaned fails
       if res is None and full_address:
           fallback_q = f"{full_address}, Metro Manila, Philippines"
           out.at[i, "fallback_query"] = fallback_q
           try:
               res = geocode_google_quality(fallback_q)
           except Exception as e:
               print(f"[WARN] Google error row {i} fallback: {e}")
               res = None
           note_suffix = "FALLBACK_FULL"
       else:
           note_suffix = "CLEANED"
       if res:
           out.at[i, "lat"] = res["lat"]
           out.at[i, "lon"] = res["lon"]
           out.at[i, "geocode_provider"] = res["provider"]
           out.at[i, "formatted_address"] = res.get("formatted_address", "")
           out.at[i, "quality_note"] = f"{note_suffix}|{res.get('location_type','')}"
   return out

In [54]:
# =========================
# CRS handling
# =========================

def to_geodataframe(
   df_with_coords: pd.DataFrame,
   lon_col: str = "lon",
   lat_col: str = "lat",
   source_crs: str = SOURCE_CRS,
   target_crs: T.Optional[str] = ANALYSIS_CRS,
) -> gpd.GeoDataFrame:
   gdf = gpd.GeoDataFrame(
       df_with_coords.copy(),
       geometry=[
           Point(xy) if pd.notna(xy[0]) and pd.notna(xy[1]) else None
           for xy in zip(df_with_coords[lon_col], df_with_coords[lat_col])
       ],
       crs=source_crs
   )
   gdf = gdf[~gdf["geometry"].isna()].copy()
   if target_crs:
       gdf = gdf.to_crs(target_crs)
   return gdf

In [ ]:
result = geocode_google_batch(
       df,
       full_address_col="full_address",
       force_mm_tail=True
   )

result.to_csv("geocoded-data.csv", index=False)

In [56]:
result

,project_name,location,full_address,cleaned_address,cleaned_query,fallback_query,lat,lon,geocode_provider,formatted_address,quality_note
0,100 West,"Pio Del Pilar, Makati, Metro Manila","100 West, Pio Del Pilar, Makati, Metro Manila,...",100 west pio del pilar makati metro manila phi...,100 west pio del pilar makati metro manila phi...,"100 West, Pio Del Pilar, Makati, Metro Manila,...",14.558432,121.009859,google,"100 Sen. Gil Puyat Ave. Corner Washington St.,...",FALLBACK_FULL|GEOMETRIC_CENTER
1,100 West Makati,"Pio Del Pilar, Makati, Metro Manila","100 West Makati, Pio Del Pilar, Makati, Metro ...",100 west makati pio del pilar makati metro man...,100 west makati pio del pilar makati metro man...,<NA>,14.558432,121.009859,google,"100 Sen. Gil Puyat Ave. Corner Washington St.,...",CLEANED|GEOMETRIC_CENTER
2,1001 Parkway Residences,"Muntinlupa, Metro Manila","1001 Parkway Residences, Muntinlupa, Metro Man...",1001 parkway muntinlupa metro manila philippines,1001 parkway muntinlupa metro manila philippines,<NA>,14.414123,121.037205,google,"C27P+JVW, Muntinlupa, Metro Manila, Philippines",CLEANED|GEOMETRIC_CENTER
3,101 Newport BLVD,"Pasay, Metro Manila","101 Newport BLVD, Pasay, Metro Manila, Philipp...",101 newport boulevard pasay metro manila phili...,101 newport boulevard pasay metro manila phili...,<NA>,14.523773,121.012999,google,"101 Newport Blvd, Newport City, Pasay City, Me...",CLEANED|ROOFTOP
4,101 Xavierville,"Loyola Heights, Quezon City, Metro Manila","101 Xavierville, Loyola Heights, Quezon City, ...",101 xavierville loyola heights quezon city met...,101 xavierville loyola heights quezon city met...,<NA>,14.634115,121.073414,google,"101 Xavierville Ave, Diliman, Quezon City, 110...",CLEANED|ROOFTOP
...,...,...,...,...,...,...,...,...,...,...,...
1011,dakotaresidences,"Tugatog, Malabon, Metro Manila","dakotaresidences, Tugatog, Malabon, Metro Mani...",dakotaresidences tugatog malabon metro manila ...,dakotaresidences tugatog malabon metro manila ...,"dakotaresidences, Tugatog, Malabon, Metro Mani...",<NA>,<NA>,<NA>,<NA>,<NA>
1012,mckinley hill garden villas,"Bagong Tanyag, Taguig, Metro Manila","mckinley hill garden villas, Bagong Tanyag, Ta...",mckinley hill garden villas bagong tanyag tagu...,mckinley hill garden villas bagong tanyag tagu...,"mckinley hill garden villas, Bagong Tanyag, Ta...",<NA>,<NA>,<NA>,<NA>,<NA>
1013,oriental gardens makati,"Bangkal, Makati, Metro Manila","oriental gardens makati, Bangkal, Makati, Metr...",oriental gardens makati bangkal makati metro m...,oriental gardens makati bangkal makati metro m...,"oriental gardens makati, Bangkal, Makati, Metr...",<NA>,<NA>,<NA>,<NA>,<NA>
1014,symfoni kamias,"Ramon Magsaysay, Quezon City, Metro Manila","symfoni kamias, Ramon Magsaysay, Quezon City, ...",symfoni kamias ramon magsaysay quezon city met...,symfoni kamias ramon magsaysay quezon city met...,"symfoni kamias, Ramon Magsaysay, Quezon City, ...",<NA>,<NA>,<NA>,<NA>,<NA>
1015,trump tower,"Makati, Metro Manila","trump tower, Makati, Metro Manila, Philippines",trump tower makati metro manila philippines,trump tower makati metro manila philippines,<NA>,14.565145,121.028332,google,"Makati Ave, Makati City, Metro Manila, Philipp...",CLEANED|GEOMETRIC_CENTER