In [65]:
input_csv = "data_others/train-stations.csv"
full_address_col = "full_address"
output_csv = "initial_poc/geocoded-train-stations.csv"

In [66]:
import pandas as pd

# read csv file 
df = pd.read_csv(input_csv)

In [67]:
# =========================
# Address cleaning & standardization
# =========================
import re

_ABBR_MAP = [
   (r"\bbrgy\b", "barangay"),
   (r"\bbrg[y.]?\b", "barangay"),
   (r"\bst\b", "street"),
   (r"\brd\b", "road"),
   (r"\bave\b", "avenue"),
   (r"\bav\b", "avenue"),
   (r"\bblvd\b", "boulevard"),
   (r"\bflr\b", "floor"),
   (r"\bph\b", "penthouse"),
]

# High-signal Manila terms
_SYNONYM_MAP = [
   (r"\bbgc\b", "bonifacio global city"),
   (r"\bfort\b", "fort bonifacio"),
   (r"\bmakati\s*cbd\b", "makati central business district"),
   (r"\bqc\b", "quezon city"),
]

# Words that rarely help geocoders and often add noise; remove as standalone tokens
_NOISE_TOKENS = [
   "condominium", "condominiums", "residences", "residence", "tower", "towers",
   "phase", "blk", "block", "lot", "unit", "bldg", "building", "subdivision",
   "village"  # keep if it's the only locator; we handle cautiously below
]
def _normalize_space(s: str) -> str:
   s = re.sub(r"[,\|;/\\]+", " ", s)      # unify separators to space
   s = re.sub(r"\s+", " ", s).strip()
   return s

def _strip_diacritics_basic(s: str) -> str:
   return (s.replace("ñ", "n")
            .replace("á","a").replace("à","a").replace("â","a")
            .replace("é","e").replace("è","e").replace("ê","e")
            .replace("í","i").replace("ì","i").replace("î","i")
            .replace("ó","o").replace("ò","o").replace("ô","o")
            .replace("ú","u").replace("ù","u").replace("û","u"))

def _apply_map_pairs(s: str, pairs) -> str:
   for pat, repl in pairs:
       s = re.sub(pat, repl, s)
   return s

def clean_address_freeform(addr: str) -> str:
   """
   Conservative cleaner for a single-string address.
   Keeps districts/landmarks like 'Ayala Triangle' or 'Greenbelt' if no street exists.
   """
   if not addr:
       return ""
   x = _normalize_space(_strip_diacritics_basic(addr.lower()))
   # Expand abbreviations and synonyms
   x = _apply_map_pairs(x, _ABBR_MAP)
   x = _apply_map_pairs(x, _SYNONYM_MAP)
   tokens = x.split(" ")
   # If we have a street number / street keyword, we can safely drop noise tokens
   has_street_signal = any(t.isdigit() for t in tokens) or any(
       kw in x for kw in ["street", "road", "avenue", "drive", "highway", "hwy", "lane"]
   )
   if has_street_signal:
       tokens = [t for t in tokens if t not in _NOISE_TOKENS]
   x = " ".join(tokens)
   x = _normalize_space(x)
   return x

def compose_query(address: str,
                 city: str = "",
                 barangay: str = "",
                 force_mm_tail: bool = True) -> str:
   """
   Build a geocode query with optional admin tail.
   If city/barangay are present, append them; otherwise pass address as-is.
   """
   parts = []
   addr_clean = clean_address_freeform(address)
   if addr_clean:
       parts.append(addr_clean)
   brgy_clean = clean_address_freeform(barangay) if barangay else ""
   city_clean = clean_address_freeform(city) if city else ""
   # Avoid duplicating if already included
   if brgy_clean and brgy_clean not in addr_clean:
       parts.append(brgy_clean)
   if city_clean and city_clean not in addr_clean:
       parts.append(city_clean)
   if force_mm_tail:
       tail = "metro manila philippines"
       if tail not in addr_clean:
           parts.append(tail)
   q = _normalize_space(" ".join(parts))
   return q

In [68]:
df

,line,station,station_name,address,full_address
0,MRT-3,North Avenue,MRT-3 North Avenue Station,"North Avenue, Quezon City, Metro Manila","MRT-3 North Avenue Station, North Avenue, Quez..."
1,MRT-3,Quezon Avenue,MRT-3 Quezon Avenue (South Bound) Station,"1103 Epifanio de los Santos Ave, Diliman, Quez...","MRT-3 Quezon Avenue (South Bound) Station, 110..."
2,MRT-3,GMA–Kamuning,MRT-3 Kamuning Station,"32 Samar Ave, Diliman, Quezon City, 1103 Metro...","MRT-3 Kamuning Station, 32 Samar Ave, Diliman,..."
3,MRT-3,Araneta Center–Cubao,MRT-3 Araneta Center - Cubao Station,"Epifanio de los Santos Ave, Cubao, Quezon City...","MRT-3 Araneta Center - Cubao Station, Epifanio..."
4,MRT-3,Santolan–Annapolis,Santolan-annapolis,"Epifanio de los Santos Ave, San Juan City, 150...","Santolan-annapolis, Epifanio de los Santos Ave..."
5,MRT-3,Ortigas,MRT-3 Ortigas Station,"Ortigas, Mandaluyong City, Metro Manila","MRT-3 Ortigas Station, Ortigas, Mandaluyong Ci..."
6,MRT-3,Shaw Boulevard,MRT-3 Shaw Boulevard Station,"Shaw Boulevard, Mandaluyong City, Metro Manila","MRT-3 Shaw Boulevard Station, Shaw Boulevard, ..."
7,MRT-3,Guadalupe,MRT-3 Guadalupe Footbridge,"H29W+28J, Guijo, Makati, Kalakhang Maynila","MRT-3 Guadalupe Footbridge, H29W+28J, Guijo, M..."
8,MRT-3,Gil Puyat,Buendia MRT,"Makati City, Metro Manila","Buendia MRT, Makati City, Metro Manila"
9,MRT-3,Ayala,MRT-3 Ayala Avenue Station,"McKinley Rd, Makati City, Metro Manila","MRT-3 Ayala Avenue Station, McKinley Rd, Makat..."
10,MRT-3,Magallanes,MRT-3 Magallanes Station,"Epifanio de los Santos Ave, Makati City, Metro...","MRT-3 Magallanes Station, Epifanio de los Sant..."
11,MRT-3,Taft Avenue,MRT-3 Taft Avenue Station,"Epifanio de los Santos Ave, Pasay City, 1300 M...","MRT-3 Taft Avenue Station, Epifanio de los San..."
12,LRT-1,Fernando Poe Jr.,Roosevelt Station,"1039 Epifanio de los Santos Ave, Bago Bantay, ...","Roosevelt Station, 1039 Epifanio de los Santos..."
13,LRT-1,Balintawak,LRT Line 1 Balintawak,"M243+XFG, Quezon City, Metro Manila","LRT Line 1 Balintawak, M243+XFG, Quezon City, ..."
14,LRT-1,Monumento,Monumento LRT Station,"Grace Park West, Caloocan, Metro Manila","Monumento LRT Station, Grace Park West, Calooc..."
15,LRT-1,5th Avenue,5th Avenue lrt station,"JXVP+P2X lrt station, 5th Ave, Grace Park East...","5th Avenue lrt station, JXVP+P2X lrt station, ..."
16,LRT-1,R. Papa,R. Papa Station,"Ricardo Papa St, Santa Cruz, Manila, Metro Manila","R. Papa Station, Ricardo Papa St, Santa Cruz, ..."
17,LRT-1,Abad Santos,Abad Santos LRT Station,"Mt. Samat, Tondo, Manila, Metro Manila","Abad Santos LRT Station, Mt. Samat, Tondo, Man..."
18,LRT-1,Blumentritt,Blumentritt LRT Station,"Santa Cruz, Manila, Metro Manila","Blumentritt LRT Station, Santa Cruz, Manila, M..."
19,LRT-1,Tayuman,Tayuman LRT Station,"JX8M+J38, R-9, Santa Cruz, Manila, 1008 Metro ...","Tayuman LRT Station, JX8M+J38, R-9, Santa Cruz..."
20,LRT-1,Bambang,Bambang LRT Station,"Santa Cruz, Manila, Metro Manila","Bambang LRT Station, Santa Cruz, Manila, Metro..."
21,LRT-1,Doroteo Jose,Doroteo Jose LRT Station,"Rizal Ave, Santa Cruz, Manila, 1008 Metro Manila","Doroteo Jose LRT Station, Rizal Ave, Santa Cru..."
22,LRT-1,Carriedo,Carriedo LRT Station,"Carriedo St, Quiapo, Manila, 1001 Metro Manila","Carriedo LRT Station, Carriedo St, Quiapo, Man..."
23,LRT-1,Central Terminal,Central Terminal LRT Station,"Ermita, Manila, 1000 Metro Manila","Central Terminal LRT Station, Ermita, Manila, ..."
24,LRT-1,UN Avenue,United Nations Station,"Taft Ave, Ermita, Manila, 1000 Metro Manila","United Nations Station, Taft Ave, Ermita, Mani..."
25,LRT-1,Pedro Gil,Pedro Gil Station,"Taft Ave, Ermita, Manila, 1000 Metro Manila","Pedro Gil Station, Taft Ave, Ermita, Manila, 1..."
26,LRT-1,Quirino,Quirino LRT Station,"Malate, Manila, 1004 Metro Manila","Quirino LRT Station, Malate, Manila, 1004 Metr..."
27,LRT-1,Vito Cruz,Vito Cruz LRT Station,"Malate, Manila, 1004 Metro Manila","Vito Cruz LRT Station, Malate, Manila, 1004 Me..."
28,LRT-1,Gil Puyat,Gil Puyat LRT Station,"Pasay City, Metro Manila","Gil Puyat LRT Station, Pasay City, Metro Manila"
29,LRT-1,Libertad,LRT LIBERTAD STATION North Bound,"GXXX+4FQ, Antonio S. Arnaiz Avenue, Taft Ave, ...","LRT LIBERTAD STATION North Bound, GXXX+4FQ, An..."
30,LRT-1,EDSA-Taft,Metro Rail Transit (MRT) / Light Rail Transit ...,"EDSA - Pasay Rotonda Foot Bridge, Pasay City, ...",Metro Rail Transit (MRT) / Light Rail Transit ...
31,LRT-1,Baclaran,LRT 1 Baclaran Station,"Taft Ave Ext, Pasay City, Metro Manila","LRT 1 Baclaran Station, Taft Ave Ext, Pasay Ci..."
32,LRT-1,Redemptorist–Aseana,LRT 1 - Redemptorist Aseana Station,"4889 Roxas Blvd, Parañaque, Metro Manila","LRT 1 - Redemptorist Aseana Station, 4889 Roxa..."
33,LRT-1,MIA Road,MIA Road LRT Station,"8355 Roxas Blvd, Parañaque, Metro Manila","MIA Road LRT Station, 8355 Roxas Blvd, Parañaq..."
34,LRT-1,Asia World (PITX),LRT 1 - Asia World (PITX) Station,"102 Kennedy Road, Parañaque, Metro Manila","LRT 1 - Asia World (PITX) Station, 102 Kennedy..."
35,LRT-1,Ninoy Aquino,LRT 1 - Ninoy Aquino Station - Parañaque City NCR,"Ninoy Aquino Ave, Parañaque, Metro Manila",LRT 1 - Ninoy Aquino Station - Parañaque City ...
36,LRT-1,Dr. Santos,LRT 1 - Dr. Santos Station - Parañaque City NCR,"FXPQ+4WF, San Dionisio, 1700 Metro Manila",LRT 1 - Dr. Santos Station - Parañaque City NC...
37,LRT-2,Recto,LRT 2 - Recto Station,"1655 Recto Ave, Santa Cruz, Manila, 1003 Metro...","LRT 2 - Recto Station, 1655 Recto Ave, Santa C..."
38,LRT-2,Legarda,LRT 2 - Legarda Station - Manila City,"JX2V+82W, Sampaloc, Manila, 1008 Metro Manila","LRT 2 - Legarda Station - Manila City, JX2V+82..."
39,LRT-2,Pureza,Pureza Station,"3303 Magsaysay Blvd Sampaloc, Manila 1008 Mags...","Pureza Station, 3303 Magsaysay Blvd Sampaloc, ..."
40,LRT-2,V. Mapa,V. Mapa,"Santa Mesa Blvd, Santa Mesa, Manila, Metro Manila","V. Mapa, Santa Mesa Blvd, Santa Mesa, Manila, ..."
41,LRT-2,J. Ruiz,LRT-2 J. Ruiz Station,"San Juan City, Metro Manila","LRT-2 J. Ruiz Station, San Juan City, Metro Ma..."
42,LRT-2,Gilmore,Gilmore Station,"Quezon City, Metro Manila","Gilmore Station, Quezon City, Metro Manila"
43,LRT-2,Betty Go–Belmonte,LRT 2 - BettyGo Belmonte Station - Quezon City,"768 Aurora Blvd, Quezon City, 1111 Metro Manila",LRT 2 - BettyGo Belmonte Station - Quezon City...
44,LRT-2,Cubao,Cubao LRT-2 Station,"70 Aurora Blvd, Quezon City, 1102 Metro Manila","Cubao LRT-2 Station, 70 Aurora Blvd, Quezon Ci..."
45,LRT-2,Anonas,LRT-2 Anonas Station,"Aurora Blvd, Project 3, Quezon City, Metro Manila","LRT-2 Anonas Station, Aurora Blvd, Project 3, ..."
46,LRT-2,Katipunan,LRT 2 - Katipunan Station - Quezon City,"977 Aurora Blvd, Project 3, Quezon City, 1109 ...","LRT 2 - Katipunan Station - Quezon City, 977 A..."
47,LRT-2,Santolan,BPI LRT 2 Santolan Station ATM,"LRT Santolan Station, Quezon City, Quezon City...","BPI LRT 2 Santolan Station ATM, LRT Santolan S..."
48,LRT-2,Marikina-Pasig,LRT 2 - Marikina–Pasig Station,"1800 Marikina-Infanta Hwy, Marikina, 1800 Metr...","LRT 2 - Marikina–Pasig Station, 1800 Marikina-..."
49,LRT-2,Antipolo,SM City Masinag,"SM City, Infanta Hwy, Masinag, Antipolo City, ...","SM City Masinag, SM City, Infanta Hwy, Masinag..."
50,PNR,Tutuban,Tutuban Station Parking,"JX6F+98C, Tondo, Manila, Metro Manila","Tutuban Station Parking, JX6F+98C, Tondo, Mani..."
51,PNR,Blumentritt,PNR Blumentritt Station,"1606 Antipolo St, Santa Cruz, Manila, 1014 Met...","PNR Blumentritt Station, 1606 Antipolo St, San..."
52,PNR,Pandacan,PNR Pandacan Station,"Tomos Claudio, Pandacan, Manila, 1011 Metro Ma...","PNR Pandacan Station, Tomos Claudio, Pandacan,..."
53,PNR,Paco,Paco PNR Station,"HXHX+QQV, C-2, Paco, Manila, Metro Manila","Paco PNR Station, HXHX+QQV, C-2, Paco, Manila,..."
54,PNR,San Andres,PNR San Andres Station,"Aviadores, San Andres Bukid, Manila, Metro Manila","PNR San Andres Station, Aviadores, San Andres ..."
55,PNR,Vito Cruz,PNR Vito Cruz Station,"P.Ocampo St., San Andres, Manila, Metro Manila","PNR Vito Cruz Station, P.Ocampo St., San Andre..."

In [69]:
import time, requests, typing as T, geopandas as gpd
from shapely.geometry import Point

# =========================
# Config
# =========================

GOOGLE_KEY = "AIzaSyATTWZx0JUPqeaHjm718D0SZsrA5T16kOI"
COUNTRY_2 = "PH"
USER_AGENT = "PH-Geocoder/1.0 (contact: dvpagcaliwagan@up.edu.ph)"

# Metro Manila bounding box (lon_min, lat_min, lon_max, lat_max)
MM_BBOX = (120.85, 14.00, 121.20, 14.90)

SOURCE_CRS = "EPSG:4326"   # WGS84
ANALYSIS_CRS = "EPSG:32651"  # UTM Zone 51N
MAX_RETRIES = 4
BACKOFF_BASE_SEC = 1.5

# =========================
# Utility functions
# =========================

def in_bbox(lon: float, lat: float, bbox=MM_BBOX) -> bool:
   x0, y0, x1, y1 = bbox
   return (x0 <= lon <= x1) and (y0 <= lat <= y1)

def backoff_sleep(try_idx: int):
   delay = BACKOFF_BASE_SEC * (2 ** try_idx)
   time.sleep(delay + 0.25 * (try_idx + 1))

In [70]:
# =========================
# Google Geocoding API
# =========================

def google_geocode_request(query: str, country_2: str = COUNTRY_2) -> dict:
   if not GOOGLE_KEY:
       raise RuntimeError("GOOGLE_MAPS_API_KEY not set.")
   url = "https://maps.googleapis.com/maps/api/geocode/json"
   params = {
       "address": query,
       "components": f"country:{country_2}",
       "key": GOOGLE_KEY,
   }
   headers = {"User-Agent": USER_AGENT}
   last_err = None
   for t in range(MAX_RETRIES):
       try:
           r = requests.get(url, params=params, headers=headers, timeout=30)
           r.raise_for_status()
           data = r.json()
           status = data.get("status", "")
           if status == "OK":
               return data
           elif status in {"OVER_DAILY_LIMIT", "OVER_QUERY_LIMIT", "UNKNOWN_ERROR"}:
               backoff_sleep(t)
               last_err = RuntimeError(f"Google status: {status}")
               continue
           elif status == "ZERO_RESULTS":
               return data
           else:
               raise RuntimeError(f"Google status: {status}, error: {data.get('error_message')}")
       except requests.RequestException as e:
           last_err = e
           backoff_sleep(t)
   if last_err:
       raise last_err
   return {"status": "ZERO_RESULTS", "results": []}

def pick_google_candidate(results: list) -> T.Optional[dict]:
   for r in results:
       if r.get("partial_match", False):
           continue
       geom = r.get("geometry", {})
       lt = geom.get("location_type", "")
       if lt not in {"ROOFTOP", "GEOMETRIC_CENTER"}:
           continue
       loc = geom.get("location", {})
       lat = float(loc.get("lat"))
       lon = float(loc.get("lng"))
       if not in_bbox(lon, lat):
           continue
       return {
           "provider": "google",
           "formatted_address": r.get("formatted_address", ""),
           "lat": lat,
           "lon": lon,
           "location_type": lt,
           "place_id": r.get("place_id"),
           "types": ",".join(r.get("types", []))
       }
   return None

def geocode_google_quality(query: str) -> T.Optional[dict]:
   data = google_geocode_request(query)
   if data.get("status") != "OK":
       return None
   return pick_google_candidate(data.get("results", []))

In [71]:
# =========================
# Batch pipeline (Google only + fallback)
# =========================

def geocode_google_batch(
   df: pd.DataFrame,
   full_address_col: str,
   city_col: T.Optional[str] = None,
   barangay_col: T.Optional[str] = None,
   force_mm_tail: bool = True
) -> pd.DataFrame:
   out = df.copy()
   for c in ["cleaned_query", "fallback_query", "lat", "lon", "geocode_provider", "formatted_address", "quality_note"]:
       if c not in out.columns:
           out[c] = pd.NA
   for i, row in out.iterrows():
       full_address = str(row[full_address_col]) if pd.notna(row[full_address_col]) else ""
       raw_city = str(row[city_col]) if city_col and pd.notna(row[city_col]) else ""
       raw_brgy = str(row[barangay_col]) if barangay_col and pd.notna(row[barangay_col]) else ""
       
       # Primary query: cleaned address
       cleaned_query = compose_query(full_address, city=raw_city, barangay=raw_brgy, force_mm_tail=force_mm_tail)
       out.at[i, "cleaned_query"] = cleaned_query
       if not cleaned_query:
           continue
       try:
           res = geocode_google_quality(cleaned_query)
       except Exception as e:
           print(f"[WARN] Google error row {i} cleaned: {e}")
           res = None
       # Fallback: use full raw address if cleaned fails
       if res is None and full_address:
           fallback_q = f"{full_address}, Metro Manila, Philippines"
           out.at[i, "fallback_query"] = fallback_q
           try:
               res = geocode_google_quality(fallback_q)
           except Exception as e:
               print(f"[WARN] Google error row {i} fallback: {e}")
               res = None
           note_suffix = "FALLBACK_FULL"
       else:
           note_suffix = "CLEANED"
       if res:
           out.at[i, "lat"] = res["lat"]
           out.at[i, "lon"] = res["lon"]
           out.at[i, "geocode_provider"] = res["provider"]
           out.at[i, "formatted_address"] = res.get("formatted_address", "")
           out.at[i, "quality_note"] = f"{note_suffix}|{res.get('location_type','')}"
   return out

In [72]:
# =========================
# CRS handling
# =========================

def to_geodataframe(
   df_with_coords: pd.DataFrame,
   lon_col: str = "lon",
   lat_col: str = "lat",
   source_crs: str = SOURCE_CRS,
   target_crs: T.Optional[str] = ANALYSIS_CRS,
) -> gpd.GeoDataFrame:
   gdf = gpd.GeoDataFrame(
       df_with_coords.copy(),
       geometry=[
           Point(xy) if pd.notna(xy[0]) and pd.notna(xy[1]) else None
           for xy in zip(df_with_coords[lon_col], df_with_coords[lat_col])
       ],
       crs=source_crs
   )
   gdf = gdf[~gdf["geometry"].isna()].copy()
   if target_crs:
       gdf = gdf.to_crs(target_crs)
   return gdf

In [73]:
result = geocode_google_batch(
       df,
       full_address_col=full_address_col,
       force_mm_tail=True
   )

result.to_csv(output_csv, index=False)

In [74]:
result

,line,station,station_name,address,full_address,cleaned_query,fallback_query,lat,lon,geocode_provider,formatted_address,quality_note
0,MRT-3,North Avenue,MRT-3 North Avenue Station,"North Avenue, Quezon City, Metro Manila","MRT-3 North Avenue Station, North Avenue, Quez...",mrt-3 north avenue station north avenue quezon...,<NA>,14.65217,121.032333,google,"North Avenue, Quezon City, Metro Manila, Phili...",CLEANED|GEOMETRIC_CENTER
1,MRT-3,Quezon Avenue,MRT-3 Quezon Avenue (South Bound) Station,"1103 Epifanio de los Santos Ave, Diliman, Quez...","MRT-3 Quezon Avenue (South Bound) Station, 110...",mrt-3 quezon avenue (south bound) station 1103...,<NA>,14.64276,121.038508,google,"Quezon Avenue, 1103 Epifanio de los Santos Ave...",CLEANED|ROOFTOP
2,MRT-3,GMA–Kamuning,MRT-3 Kamuning Station,"32 Samar Ave, Diliman, Quezon City, 1103 Metro...","MRT-3 Kamuning Station, 32 Samar Ave, Diliman,...",mrt-3 kamuning station 32 samar avenue diliman...,<NA>,14.635217,121.043343,google,"GMA Kamuning Station, 32 Samar Ave, Diliman, Q...",CLEANED|ROOFTOP
3,MRT-3,Araneta Center–Cubao,MRT-3 Araneta Center - Cubao Station,"Epifanio de los Santos Ave, Cubao, Quezon City...","MRT-3 Araneta Center - Cubao Station, Epifanio...",mrt-3 araneta center - cubao station epifanio ...,<NA>,14.619488,121.051131,google,"Araneta Center - Cubao Station, Epifanio de lo...",CLEANED|GEOMETRIC_CENTER
4,MRT-3,Santolan–Annapolis,Santolan-annapolis,"Epifanio de los Santos Ave, San Juan City, 150...","Santolan-annapolis, Epifanio de los Santos Ave...",santolan-annapolis epifanio de los santos aven...,<NA>,14.607331,121.05643,google,"Santolan-annapolis, Abenida Epifanio de los Sa...",CLEANED|GEOMETRIC_CENTER
5,MRT-3,Ortigas,MRT-3 Ortigas Station,"Ortigas, Mandaluyong City, Metro Manila","MRT-3 Ortigas Station, Ortigas, Mandaluyong Ci...",mrt-3 ortigas station ortigas mandaluyong city...,<NA>,14.587952,121.056651,google,"Ortigas, Mandaluyong City, Metro Manila, Phili...",CLEANED|GEOMETRIC_CENTER
6,MRT-3,Shaw Boulevard,MRT-3 Shaw Boulevard Station,"Shaw Boulevard, Mandaluyong City, Metro Manila","MRT-3 Shaw Boulevard Station, Shaw Boulevard, ...",mrt-3 shaw boulevard station shaw boulevard ma...,<NA>,14.581206,121.053597,google,"Shaw Boulevard, Mandaluyong City, Metro Manila...",CLEANED|GEOMETRIC_CENTER
7,MRT-3,Guadalupe,MRT-3 Guadalupe Footbridge,"H29W+28J, Guijo, Makati, Kalakhang Maynila","MRT-3 Guadalupe Footbridge, H29W+28J, Guijo, M...",mrt-3 guadalupe footbridge h29w+28j guijo maka...,<NA>,14.567599,121.045766,google,"H29W+28J, Guijo, Makati, Kalakhang Maynila, Ph...",CLEANED|GEOMETRIC_CENTER
8,MRT-3,Gil Puyat,Buendia MRT,"Makati City, Metro Manila","Buendia MRT, Makati City, Metro Manila",buendia mrt makati city metro manila metro man...,<NA>,14.554422,121.034349,google,"Buendia station, Makati City, Metro Manila, Ph...",CLEANED|GEOMETRIC_CENTER
9,MRT-3,Ayala,MRT-3 Ayala Avenue Station,"McKinley Rd, Makati City, Metro Manila","MRT-3 Ayala Avenue Station, McKinley Rd, Makat...",mrt-3 ayala avenue station mckinley road makat...,<NA>,14.549034,121.028251,google,"MRT-3 Ayala Avenue Station, McKinley Rd, Makat...",CLEANED|GEOMETRIC_CENTER
10,MRT-3,Magallanes,MRT-3 Magallanes Station,"Epifanio de los Santos Ave, Makati City, Metro...","MRT-3 Magallanes Station, Epifanio de los Sant...",mrt-3 magallanes station epifanio de los santo...,<NA>,14.542023,121.019485,google,"Magallanes Station, Epifanio de los Santos Ave...",CLEANED|GEOMETRIC_CENTER
11,MRT-3,Taft Avenue,MRT-3 Taft Avenue Station,"Epifanio de los Santos Ave, Pasay City, 1300 M...","MRT-3 Taft Avenue Station, Epifanio de los San...",mrt-3 taft avenue station epifanio de los sant...,<NA>,14.537669,121.002175,google,"Taft Avenue, Epifanio de los Santos Ave, Pasay...",CLEANED|GEOMETRIC_CENTER
12,LRT-1,Fernando Poe Jr.,Roosevelt Station,"1039 Epifanio de los Santos Ave, Bago Bantay, ...","Roosevelt Station, 1039 Epifanio de los Santos...",roosevelt station 1039 epifanio de los santos ...,<NA>,14.657605,121.021101,google,"Roosevelt Station, 1039 Epifanio de los Santos...",CLEANED|ROOFTOP
13,LRT-1,Balintawak,LRT Line 1 Balintawak,"M243+XFG, Quezon City, Metro Manila","LRT Line 1 Balintawak, M243+XFG, Quezon City, ...",lrt line 1 balintawak m243+xfg quezon city met...,<NA>,14.657427,121.003697,google,"M243+XFG, Quezon City, Metro Manila, Philippines",CLEANED|GEOMETRIC_CENTER
14,LRT-1,Monumento,Monumento LRT Station,"Grace Park West, Caloocan, Metro Manila","Monumento LRT Station, Grace Park West, Calooc...",monumento lrt station grace park west caloocan...,<NA>,14.654367,120.983894,google,"Monumento, Grace Park West, Caloocan, Metro Ma...",CLEANED|GEOMETRIC_CENTER
15,LRT-1,5th Avenue,5th Avenue lrt station,"JXVP+P2X lrt station, 5th Ave, Grace Park East...","5th Avenue lrt station, JXVP+P2X lrt station, ...",5th avenue lrt station jxvp+p2x lrt station 5t...,<NA>,14.644363,120.9851,google,"JXVP+P2X lrt station, 5th Ave, Grace Park East...",CLEANED|GEOMETRIC_CENTER
16,LRT-1,R. Papa,R. Papa Station,"Ricardo Papa St, Santa Cruz, Manila, Metro Manila","R. Papa Station, Ricardo Papa St, Santa Cruz, ...",r. papa station ricardo papa street santa cruz...,"R. Papa Station, Ricardo Papa St, Santa Cruz, ...",14.636153,120.982342,google,"R. Papa, Ricardo Papa St, Santa Cruz, Manila, ...",FALLBACK_FULL|GEOMETRIC_CENTER
17,LRT-1,Abad Santos,Abad Santos LRT Station,"Mt. Samat, Tondo, Manila, Metro Manila","Abad Santos LRT Station, Mt. Samat, Tondo, Man...",abad santos lrt station mt. samat tondo manila...,<NA>,14.630586,120.981422,google,"Abad Santos, Mt. Samat, Tondo, Manila, Metro M...",CLEANED|GEOMETRIC_CENTER
18,LRT-1,Blumentritt,Blumentritt LRT Station,"Santa Cruz, Manila, Metro Manila","Blumentritt LRT Station, Santa Cruz, Manila, M...",blumentritt lrt station santa cruz manila metr...,<NA>,14.622746,120.983535,google,"Blumentritt station, Santa Cruz, Manila, Metro...",CLEANED|GEOMETRIC_CENTER
19,LRT-1,Tayuman,Tayuman LRT Station,"JX8M+J38, R-9, Santa Cruz, Manila, 1008 Metro ...","Tayuman LRT Station, JX8M+J38, R-9, Santa Cruz...",tayuman lrt station jx8m+j38 r-9 santa cruz ma...,<NA>,14.616533,120.98271,google,"JX8M+J38, R-9, Santa Cruz, Manila, 1008 Metro ...",CLEANED|GEOMETRIC_CENTER
20,LRT-1,Bambang,Bambang LRT Station,"Santa Cruz, Manila, Metro Manila","Bambang LRT Station, Santa Cruz, Manila, Metro...",bambang lrt station santa cruz manila metro ma...,<NA>,14.611099,120.982494,google,"Bambang LRT Station, Santa Cruz, Manila, Metro...",CLEANED|GEOMETRIC_CENTER
21,LRT-1,Doroteo Jose,Doroteo Jose LRT Station,"Rizal Ave, Santa Cruz, Manila, 1008 Metro Manila","Doroteo Jose LRT Station, Rizal Ave, Santa Cru...",doroteo jose lrt station rizal avenue santa cr...,<NA>,14.605348,120.981973,google,"Doroteo Jose, Rizal Ave, Santa Cruz, Manila, 1...",CLEANED|GEOMETRIC_CENTER
22,LRT-1,Carriedo,Carriedo LRT Station,"Carriedo St, Quiapo, Manila, 1001 Metro Manila","Carriedo LRT Station, Carriedo St, Quiapo, Man...",carriedo lrt station carriedo street quiapo ma...,<NA>,14.599,120.98133,google,"Carriedo LRT Station, Carriedo St, Quiapo, Man...",CLEANED|GEOMETRIC_CENTER
23,LRT-1,Central Terminal,Central Terminal LRT Station,"Ermita, Manila, 1000 Metro Manila","Central Terminal LRT Station, Ermita, Manila, ...",central terminal lrt station ermita manila 100...,<NA>,14.592752,120.981633,google,"Central Terminal, Ermita, Manila, 1000 Metro M...",CLEANED|GEOMETRIC_CENTER
24,LRT-1,UN Avenue,United Nations Station,"Taft Ave, Ermita, Manila, 1000 Metro Manila","United Nations Station, Taft Ave, Ermita, Mani...",united nations station taft avenue ermita mani...,<NA>,14.58255,120.984621,google,"United Nations, Taft Ave, Ermita, Manila, 1000...",CLEANED|GEOMETRIC_CENTER
25,LRT-1,Pedro Gil,Pedro Gil Station,"Taft Ave, Ermita, Manila, 1000 Metro Manila","Pedro Gil Station, Taft Ave, Ermita, Manila, 1...",pedro gil station taft avenue ermita manila 10...,<NA>,14.576321,120.988188,google,"Pedro Gil station, Ermita, Manila, 1000 Metro ...",CLEANED|GEOMETRIC_CENTER
26,LRT-1,Quirino,Quirino LRT Station,"Malate, Manila, 1004 Metro Manila","Quirino LRT Station, Malate, Manila, 1004 Metr...",quirino lrt station malate manila 1004 metro m...,<NA>,14.5703,120.99156,google,"Quirino Station, Malate, Manila, 1004 Metro Ma...",CLEANED|GEOMETRIC_CENTER
27,LRT-1,Vito Cruz,Vito Cruz LRT Station,"Malate, Manila, 1004 Metro Manila","Vito Cruz LRT Station, Malate, Manila, 1004 Me...",vito cruz lrt station malate manila 1004 metro...,<NA>,14.563344,120.994851,google,"Vito Cruz, Malate, Manila, 1004 Metro Manila, ...",CLEANED|GEOMETRIC_CENTER
28,LRT-1,Gil Puyat,Gil Puyat LRT Station,"Pasay City, Metro Manila","Gil Puyat LRT Station, Pasay City, Metro Manila",gil puyat lrt station pasay city metro manila ...,<NA>,14.554294,120.997107,google,"Gil Puyat, Pasay City, Metro Manila, Philippines",CLEANED|GEOMETRIC_CENTER
29,LRT-1,Libertad,LRT LIBERTAD STATION North Bound,"GXXX+4FQ, Antonio S. Arnaiz Avenue, Taft Ave, ...","LRT LIBERTAD STATION North Bound, GXXX+4FQ, An...",lrt libertad station north bound gxxx+4fq anto...,"LRT LIBERTAD STATION North Bound, GXXX+4FQ, An...",14.547835,120.998729,google,"Antonio S. Arnaiz Avenue, GXXX+4FQ, Taft Ave, ...",FALLBACK_FULL|GEOMETRIC_CENTER
30,LRT-1,EDSA-Taft,Metro Rail Transit (MRT) / Light Rail Transit ...,"EDSA - Pasay Rotonda Foot Bridge, Pasay City, ...",Metro Rail Transit (MRT) / Light Rail Transit ...,metro rail transit (mrt) light rail transit (l...,<NA>,14.537935,121.00062,google,"EDSA - Pasay Rotonda Foot Bridge, Pasay City, ...",CLEANED|GEOMETRIC_CENTER
31,LRT-1,Baclaran,LRT 1 Baclaran Station,"Taft Ave Ext, Pasay City, Metro Manila","LRT 1 Baclaran Station, Taft Ave Ext, Pasay Ci...",lrt 1 baclaran station taft avenue ext pasay c...,<NA>,14.534231,120.99835,google,"Baclaran, Taft Ave Ext, Pasay City, Metro Mani...",CLEANED|GEOMETRIC_CENTER
32,LRT-1,Redemptorist–Aseana,LRT 1 - Redemptorist Aseana Station,"4889 Roxas Blvd, Parañaque, Metro Manila","LRT 1 - Redemptorist Aseana Station, 4889 Roxa...",lrt 1 - redemptorist aseana station 4889 roxas...,<NA>,14.530213,120.992823,google,"4889 Roxas Blvd, Parañaque, Metro Manila, Phil...",CLEANED|ROOFTOP
33,LRT-1,MIA Road,MIA Road LRT Station,"8355 Roxas Blvd, Parañaque, Metro Manila","MIA Road LRT Station, 8355 Roxas Blvd, Parañaq...",mia road lrt station 8355 roxas boulevard para...,<NA>,14.518081,120.993019,google,"8355 Roxas Blvd, Parañaque, Metro Manila, Phil...",CLEANED|ROOFTOP
34,LRT-1,Asia World (PITX),LRT 1 - Asia World (PITX) Station,"102 Kennedy Road, Parañaque, Metro Manila","LRT 1 - Asia World (PITX) Station, 102 Kennedy...",lrt 1 - asia world (pitx) station 102 kennedy ...,<NA>,14.508347,120.99117,google,"102 Kennedy Road, Parañaque, Metro Manila, Phi...",CLEANED|ROOFTOP
35,LRT-1,Ninoy Aquino,LRT 1 - Ninoy Aquino Station - Parañaque City NCR,"Ninoy Aquino Ave, Parañaque, Metro Manila",LRT 1 - Ninoy Aquino Station - Parañaque City ...,lrt 1 - ninoy aquino station - paranaque city ...,<NA>,14.499009,120.994282,google,"Ninoy Aquino Ave, Parañaque, Metro Manila, Phi...",CLEANED|GEOMETRIC_CENTER
36,LRT-1,Dr. Santos,LRT 1 - Dr. Santos Station - Parañaque City NCR,"FXPQ+4WF, San Dionisio, 1700 Metro Manila",LRT 1 - Dr. Santos Station - Parañaque City NC...,lrt 1 - dr. santos station - paranaque city nc...,<NA>,14.485318,120.989798,google,"FXPQ+4WF, San Dionisio, 1700 Metro Manila, Phi...",CLEANED|GEOMETRIC_CENTER
37,LRT-2,Recto,LRT 2 - Recto Station,"1655 Recto Ave, Santa Cruz, Manila, 1003 Metro...","LRT 2 - Recto Station, 1655 Recto Ave, Santa C...",lrt 2 - recto station 1655 recto avenue santa ...,<NA>,14.603515,120.983074,google,"1655 Recto Ave, Santa Cruz, Manila, 1003 Metro...",CLEANED|ROOFTOP
38,LRT-2,Legarda,LRT 2 - Legarda Station - Manila City,"JX2V+82W, Sampaloc, Manila, 1008 Metro Manila","LRT 2 - Legarda Station - Manila City, JX2V+82...",lrt 2 - legarda station - manila city jx2v+82w...,<NA>,14.600871,120.992565,google,"JX2V+82W, Sampaloc, Manila, 1008 Metro Manila,...",CLEANED|GEOMETRIC_CENTER
39,LRT-2,Pureza,Pureza Station,"3303 Magsaysay Blvd Sampaloc, Manila 1008 Mags...","Pureza Station, 3303 Magsaysay Blvd Sampaloc, ...",pureza station 3303 magsaysay boulevard sampal...,<NA>,14.601721,121.00515,google,"3303 Magsaysay Blvd Sampaloc, Manila 1008 Mags...",CLEANED|ROOFTOP
40,LRT-2,V. Mapa,V. Mapa,"Santa Mesa Blvd, Santa Mesa, Manila, Metro Manila","V. Mapa, Santa Mesa Blvd, Santa Mesa, Manila, ...",v. mapa santa mesa boulevard santa mesa manila...,<NA>,14.602876,121.015945,google,"Victorino Mapa St & Santa Mesa Blvd, Santa Mes...",CLEANED|GEOMETRIC_CENTER
41,LRT-2,J. Ruiz,LRT-2 J. Ruiz Station,"San Juan City, Metro Manila","LRT-2 J. Ruiz Station, San Juan City, Metro Ma...",lrt-2 j. ruiz station san juan city metro mani...,<NA>,14.610554,121.026208,google,"J. Ruiz Station, San Juan City, Metro Manila, ...",CLEANED|GEOMETRIC_CENTER
42,LRT-2,Gilmore,Gilmore Station,"Quezon City, Metro Manila","Gilmore Station, Quezon City, Metro Manila",gilmore station quezon city metro manila metro...,<NA>,14.613531,121.034176,google,"Gilmore Station, Quezon City, Metro Manila, Ph...",CLEANED|GEOMETRIC_CENTER
43,LRT-2,Betty Go–Belmonte,LRT 2 - BettyGo Belmonte Station - Quezon City,"768 Aurora Blvd, Quezon City, 1111 Metro Manila",LRT 2 - BettyGo Belmonte Station - Quezon City...,lrt 2 - bettygo belmonte station - quezon city...,<NA>,14.618521,121.042706,google,"768 Aurora Blvd, Quezon City, 1111 Metro Manil...",CLEANED|ROOFTOP
44,LRT-2,Cubao,Cubao LRT-2 Station,"70 Aurora Blvd, Quezon City, 1102 Metro Manila","Cubao LRT-2 Station, 70 Aurora Blvd, Quezon Ci...",cubao lrt-2 station 70 aurora boulevard quezon...,<NA>,14.622686,121.052612,google,"70 Aurora Blvd, Quezon City, 1102 Metro Manila...",CLEANED|ROOFTOP
45,LRT-2,Anonas,LRT-2 Anonas Station,"Aurora Blvd, Project 3, Quezon City, Metro Manila","LRT-2 Anonas Station, Aurora Blvd, Project 3, ...",lrt-2 anonas station aurora boulevard project ...,<NA>,14.627946,121.064705,google,"Aurora Blvd, Project 3, Quezon City, Metro Man...",CLEANED|GEOMETRIC_CENTER
46,LRT-2,Katipunan,LRT 2 - Katipunan Station - Quezon City,"977 Aurora Blvd, Project 3, Quezon City, 1109 ...","LRT 2 - Katipunan Station - Quezon City, 977 A...",lrt 2 - katipunan station - quezon city 977 au...,<NA>,14.631107,121.072502,google,"977 Aurora Blvd, Project 3, Quezon City, 1109 ...",CLEANED|ROOFTOP
47,LRT-2,Santolan,BPI LRT 2 Santolan Station ATM,"LRT Santolan Station, Quezon City, Quezon City...","BPI LRT 2 Santolan Station ATM, LRT Santolan S...",bpi lrt 2 santolan station atm lrt santolan st...,<NA>,14.62204,121.08604,google,"LRT Santolan Station, Quezon City, Quezon City...",CLEANED|GEOMETRIC_CENTER
48,LRT-2,Marikina-Pasig,LRT 2 - Marikina–Pasig Station,"1800 Marikina-Infanta Hwy, Marikina, 1800 Metr...","LRT 2 - Marikina–Pasig Station, 1800 Marikina-...",lrt 2 - marikina–pasig station 1800 marikina-i...,<NA>,14.620387,121.100275,google,"1800 Marikina-Infanta Hwy, Marikina, 1800 Metr...",CLEANED|ROOFTOP
49,LRT-2,Antipolo,SM City Masinag,"SM City, Infanta Hwy, Masinag, Antipolo City, ...","SM City Masinag, SM City, Infanta Hwy, Masinag...",sm city masinag sm city infanta hwy masinag an...,"SM City Masinag, SM City, Infanta Hwy, Masinag...",<NA>,<NA>,<NA>,<NA>,<NA>
50,PNR,Tutuban,Tutuban Station Parking,"JX6F+98C, Tondo, Manila, Metro Manila","Tutuban Station Parking, JX6F+98C, Tondo, Mani...",tutuban station parking jx6f+98c tondo manila ...,<NA>,14.610938,120.973277,google,"JX6F+98C, Tondo, Manila, Metro Manila, Philipp...",CLEANED|GEOMETRIC_CENTER
51,PNR,Blumentritt,PNR Blumentritt Station,"1606 Antipolo St, Santa Cruz, Manila, 1014 Met...","PNR Blumentritt Station, 1606 Antipolo St, San...",pnr blumentritt station 1606 antipolo street s...,<NA>,14.622605,120.983618,google,"1606 Antipolo St, Santa Cruz, Manila, 1014 Met...",CLEANED|ROOFTOP
52,PNR,Pandacan,PNR Pandacan Station,"Tomos Claudio, Pandacan, Manila, 1011 Metro Ma...","PNR Pandacan Station, Tomos Claudio, Pandacan,...",pnr pandacan station tomos claudio pandacan ma...,<NA>,14.59024,121.0088,google,"Pandacan, Tomos Claudio, Pandacan, Manila, 101...",CLEANED|GEOMETRIC_CENTER
53,PNR,Paco,Paco PNR Station,"HXHX+QQV, C-2, Paco, Manila, Metro Manila","Paco PNR Station, HXHX+QQV, C-2, Paco, Manila,...",paco pnr station hxhx+qqv c-2 paco manila metr...,<NA>,14.579495,120.999407,google,"HXHX+QQV, C-2, Paco, Manila, Metro Manila, Phi...",CLEANED|GEOMETRIC_CENTER
54,PNR,San Andres,PNR San Andres Station,"Aviadores, San Andres Bukid, Manila, Metro Manila","PNR San Andres Station, Aviadores, San Andres ...",pnr san andres station aviadores san andres bu...,<NA>,14.573246,120.999447,google,"PNR San Andres Station, Aviadores, San Andres ...",CLEANED|GEOMETRIC_CENTER
55,PNR,Vito Cruz,PNR Vito Cruz Station,"P.Ocampo St., San Andres, Manila, Metro Manila","PNR Vito Cruz Station, P.Ocampo St., San Andre...",pnr vito cruz station p.ocampo street. san and...,<NA>,14.567205,121.00284,google,"Vito Cruz, P.Ocampo St., San Andres, Manila, M...",CLEANED|GEOMETRIC_CENTER